name: Tic Tac Toe Build
on:
  push:
    paths:
    - 'Projects/Tic Tac Toe/**'
  pull_request:
    paths:
    - 'Projects/Tic Tac Toe/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: dotnet build
      run: dotnet build "Projects\Tic Tac Toe\Tic Tac Toe.csproj" --configuration Release
