name: Website Deploy
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.vscode/**'
    - '.github/**'
    - 'LICENSE'
    - 'README.md'
    - '**.md'
  workflow_dispatch:
jobs:
  deployment:
    if: ${{ github.repository == 'ZacharyPatten/dotnet-console-games' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish website
      run: dotnet publish Projects/Website/Website.csproj --configuration Release
    - name: index.html base tag
      run: sed -i 's/<base href="\/" \/>/<base href="\/dotnet-console-games\/" \/>/g' Projects/Website/bin/Release/publish/wwwroot/index.html
    - name: 404.html
      run: sed -i 's/\/?p=\//\/dotnet-console-games\/?p=\//g' Projects/Website/bin/Release/publish/wwwroot/404.html
    - name: .nojekyll
      run: touch Projects/Website/bin/Release/publish/wwwroot/.nojekyll
    - name: deploy to github-pages branch
      run: |
        cd Projects/Website/bin/Release/publish/wwwroot
        echo "* @ZacharyPatten" > CODEOWNERS
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'deploy to binaries branch'
        git push --force "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master:github-pages